import 'package:get/get.dart';

import '../translation_key.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "en": {
      greetingWord:"Hello",
      requiredFiled:"This field is required",
      invalidEmail:"This e-mail is invalid",
      invalidPassword:"This password is invalid",
      tryAgain:"Please try again later",
      noInternet:"There's no internet connection",
      openInternet:"Please open your internet and try again",
      error:"There's error happen please try again later",
      phoneNumberError:"This phone number is not valid",
      invalidReTypePassword:"passwords does not match",
      enterPasswordFirst:"You must enter the password first",
      skip: "skip",
      signUp: "sign up",
      login: "log in",
      phoneNumber: "phone number",
      password: "password",
      homePage: "home screen",
      photosAlbum: "Photo Album",
      videosAlbum: "Video Album",
      editProfile: "my profile",
      userName: "User Name",
      edit: "edit",
      more: "more",
      email: "email",
      gender: "gender",
      idNumber: "Id Number",
      city: "City",
      religion: "religion",
      docNo: "Documnet Number",
      studyYear: "Study Year",
      parentName: "Parent Name",
      nationality: "Nationality",
      job: "job",
      relation: "relation",
      bornPlace: "born Place",
      postalBox: "Postal Box",
      birthday: "birthday",
      address: "address",
      changeLang: "تغير اللغه",
      terms: "terms and conditions",
      aboutApp: "about app",
      aboutTheApp: "about the app",
      aboutTheSchool: "about the school",
      schoolVision: "School Vision",
      schoolMessage: "School Message",
      callUs: "call us",
      termsAgree: "Agree to Terms & EULA",
      changeLanguage: "change language",
      language: "language",
      newUser: "new user",
      whoAreWe: "who are we",
      policy1: "all rights are save for Rayyan School",
      policy2: "design and develop ",
      signIn: "sign in",
      back: "back",
      name: "name",
      signOut: "sign out",
      noData: "there is no data available at the moment",
      independentTeachers: "teachers",
      male: "male",
      female: "female",
      post: "all posts",
      myPosts: "my posts",
      favorites: "favorites",
      share: "share the app",
      schoolWord: "School Speach",
      send: "send",
      typeMsg: "type yout message",
      complains: "complains",
      complaientMsg: "complaient message",
      messageError: "Message Required",
      emailError: "email required",
      phoneError: "please enter your phone number",
      nameError: "please enter your name",
      news: "News",
      activity: "Activity",
      newNews: "New News",
      joinRequest: "Join Request",
      notes: "Notes",
      videoAlbum: "Video Album",
      photoAlbum: "Photo Album",
      books: "Weekly message",
      privacyPolicy: "Privacy Policy",
      homeWorks: "Home works",
      questionsBank: "Question bank",
      files: "Files",
      download: "download",
      myAccount: "My Account",
      sendMessage: "Send Message",
      results: "Results",
      questionsStudent: "Questions for Student",
      booksnref: "books and refrences",
      messages: "messages",
      schedule: "schedule",
      impProg: "Important Program",
      sentMessages: "Sent Messages",
      title: "title",
      message: "message",
      sendTo: "Send to",
      admin: "Admin",
      teacher: "Teacher",
      teacherName: "Teacher Name",
      titleError: "Title is Required",
      reports: "Reports",
      attendance: "Attendance",
      writeReport: "Write Your Report",
      reportError: "Report Required",
      sendReport: "Send Report",
      mobile: "mobile",
      oldSchool: "old school",
      joinDate: "join date",
      province: "province",
      regNum: "reg. Number",
      phone: "phone",
      regStatus: "reg. Status",
      parentJob: "parent job",
      viewVideo:"view video",
      changePass: "Change password",
      oldPass: "old password",
      newPass: "new password"
    },
    "ar": {
      greetingWord:"اهلا وسهلا بك",
      requiredFiled:"هذه الخانة مطلوبه",
      invalidEmail:"هذا البريد الإلكتروني غير صالح",
      invalidPassword:"كلمة السر هذه غير صالحة",
      tryAgain:"الرجاء معاودة المحاولة في وقت لاحق",
      noInternet:"لا يوجد اتصال بالإنترنت",
      openInternet:"الرجاء فتح الإنترنت الخاص بك وحاول مرة أخرى",
      error:"حدث خطأ ، يرجى المحاولة مرة أخرى لاحقًا",
      phoneNumberError:"رقم التلفون هذا غير صالح",
      invalidReTypePassword:"كلمه السر غير متطابقة",
      enterPasswordFirst:"يجب إدخال كلمه السر اولآ",
      skip: "تخطى",
      signUp: "تسجيل حساب جديد",
      login: "تسجيل دخول",
      phoneNumber: "رقم الهاتف",
      password: "كلمه المرور",
      homePage: "الصفحة الرئيسية",
      photosAlbum: "ألبوم الصور",
      videosAlbum: "ألبوم الفيديو",
      editProfile: "حسابى",
      userName: "اسم المستخدم",
      edit: "تعديل",
      more: "المزيد",
      name: "الاسم",
      email: "البريد الالكتروني",
      idNumber: "الرقم القومي",
      gender: "الجنس",
      birthday: "تاريخ الميلاد",
      city: "المدينة",
      religion: "الديانة",
      docNo: "رقم القيد",
      studyYear: "السنة الدراسية",
      parentName: "اسم ولي الامر",
      nationality: "الجنسية",
      job: "الوظيفة",
      relation: "صلة القرابة",
      bornPlace: "مكان الولادة",
      postalBox: "الصندوق البريدي",
      address: "عنوان السكن",
      changeLang: "change language",
      terms: "الشروط و الاحكام",
      aboutApp: "من نحن",
      aboutTheApp: "عن التطبيق",
      aboutTheSchool: "عن المدرسة",
      schoolVision: "عن المدرسة",
      schoolMessage: "رسالة المدرسة",
      callUs: "إتصل بنا",
      termsAgree: "اوافق على الشروط والأحكام",
      changeLanguage: "تغير اللغه",
      language: "اللغه",
      newUser: "مستخدم جديد",
      whoAreWe: "من نحن",
      policy1: "جميع الحقوق محفوظه لمدارس الريان الخاصة",
      policy2: "تصميم وبرمجة شركة ",
      signIn: "تسجيل الدخول",
      back: "رجوع",
      signOut: "تسجيل خروج",
      noData: "ليس هناك بيانات متاحه الأن",
      independentTeachers: "مدرسين و مدرسات",
      male: "مدرس",
      female: "مدرسة",
      post: "كل المنشورات",
      myPosts: "منشوراتي",
      favorites: "المفضله",
      share: "شارك التطبيق",
      schoolWord: "كلمة المدرسة",
      send: "إرسال",
      typeMsg: "إكتب رسالة",
      complains: "الشكاوى  و الإقتراحات",
      complaientMsg: "بامكانك إرسال الشكاوى و الاقتراحات هنا",
      messageError: "الرسالة مطلوبة",
      emailError: "البريد الالكتروني مطلوب",
      phoneError: "برجاء ادخال رقم هاتفك",
      nameError: "برجاء ادخال اسمك",
      news: "الأخبار",
      activity: "الأنشطه المدرسية",
      newNews: "جديد الأخبار",
      joinRequest: "طلب التحاق",
      notes: "ملاحظات",
      videoAlbum: "البوم الفيديو",
      photoAlbum: "البوم الصور",
      books: "الرسالة الاسبوعية",
      privacyPolicy: "سياسة الخصوصية",
      homeWorks: "الواجب المدرسي",
      questionsBank: "بنك الاسئلة",
      files: "الملفات الالكترونية",
      download: "تحميل",
      myAccount: "حسابي",
      sendMessage: "إرسال رسالة",
      results: "النتائج",
      questionsStudent: "اسئلة للطلاب",
      booksnref: "الكتب و المراجع",
      messages: "الرسائل",
      schedule: "الجدول",
      impProg: "ملفات مهمة",
      sentMessages: "الرسائل المرسلة",
      title: "عنوان الرسالة",
      message: "الرسالة",
      sendTo: "إرسال الى",
      admin: "للادارة",
      teacher: "لمدرس",
      teacherName: "أسم المدرس",
      titleError: "العنوان مطلوب",
      reports: "التقارير",
      attendance: "الغياب و الحضور",
      writeReport: "اكتب التقرير",
      reportError: "التقرير مطلوبة",
      sendReport: "إرسال تقرير",
      mobile: "الجوال",
      oldSchool: "المدرسة السابقة",
      joinDate: "تاريخ الالتحاق",
      province: "المنطقة",
      regNum: "رقم القيد",
      phone: "رقم الهاتف",
      regStatus: "حالة القيد",
      parentJob: "وظيفة ولي الامر",
      viewVideo: "مشاهدة الفيديو",
      changePass: "تغير كلمة السر",
      oldPass: "كلمة السر القديمه",
      newPass: "كلمة السر الجديده"

    }
  };
}